name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.4'
        cabal-version: '3.2'
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}

    - name: machine
      run: |
        free -h
        df -h
        lscpu

    - name: Install dependencies
      run: |
        stack build --only-dependencies --test --bench
    - name: Build
      run: stack build --test --bench
    - name: Run tests
      run: stack test
